name = "customer-account-booking-app"
client_id = "your_client_id_here"
application_url = "https://your-app-url.com"
embedded = true

[access_scopes]
# Add required scopes for customer account extensions
scopes = "write_products,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://your-app-url.com/auth/callback",
  "https://your-app-url.com/auth/shopify/callback",
  "https://your-app-url.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
